// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcfyookdsujabsfektuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZnlvb2tkc3VqYWJzZmVrdHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzU1NTAsImV4cCI6MjA1NDYxMTU1MH0.Ha3fFLAIK_WrHAqFgrv_ooDoVUTOrfp8asT9yWEbXfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});